project/pizza/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page
from . import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from .views_drf import PizzaViewSet, CartViewSet, PizzaFilterView, PizzaToCartView

router = routers.DefaultRouter()
router.register('pizza_list', PizzaViewSet)
router.register('cart_list', CartViewSet)
router.register('filter', PizzaFilterView, basename='Pizza')
router.register('pizza_to_cart', PizzaToCartView)

urlpatterns = [
    path('', cache_page(60*1)(views.PizzaHomeView.as_view()), name='home'),
    path('pizza-form-add/', views.PizzaFormAddView.as_view(), name='pizza_add'),
    path('cart/', views.PizzaCartView.as_view(), name='cart'),
    path('stop_spam_page/', TemplateView.as_view(template_name='stop_spam_page.html')),
    path('pizza-price-update/', views.PizzaPriceUpdateView.as_view(), name='price_update'),
    path('add-pizza-to-order/', views.AddPizzaToOrderView.as_view()),
    path('cart/shipping/', views.ShippingOrderView.as_view(), name='shipping'),
    path('cart/shipping/create/', views.HomePageCreateOrder.as_view(), name='create'),
    path('del_instance/<int:id>', views.AddPizzaToOrderView.del_instance, name='delete'),
    path('pizza-update/<int:pk>/edit/', views.PizzaUpdateView.as_view(), name='pizza_update'),
    path('api/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project_pizza/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('pizza.urls'))
]

project/pizza/models.py
from django.db import models


class Size(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'


class Ingredient(models.Model):
    name = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'
        ordering = ['name']


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class Pizza(models.Model):
    name = models.CharField('Название', max_length=40)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, verbose_name='Размер')
    price = models.DecimalField('Цена', max_digits=7, decimal_places=2, default=0)
    ingredient = models.ManyToManyField(Ingredient, verbose_name='Ингридиенты')
    description = models.CharField('Описание', max_length=300)
    image = models.ImageField(upload_to=image_folder)
    slug = models.SlugField()
    available = models.BooleanField('Наличие', default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Пиццу'
        verbose_name_plural = 'Пиццы'
        ordering = ['name']

    def get_serialized_pizza(self):
        return ({
            'name': self.name,
            'price': self.price,
            'size': self.size.name,
        })


class InstancePizza(models.Model):
    name = models.CharField('Название', max_length=40)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, verbose_name='Размер')
    price = models.DecimalField('Цена', max_digits=7, decimal_places=2, default=0)
    count = models.PositiveIntegerField('Количество', default=1)
    pizza_template = models.ForeignKey(Pizza, on_delete=models.CASCADE)


class Order(models.Model):
    pizzas = models.ManyToManyField(InstancePizza, blank=True)
    full_price = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    def save_full_price(self):
        pizzas = self.pizzas.all()
        full_price = 0
        for pizza in pizzas:
            full_price += pizza.price * pizza.count
        self.full_price = full_price
        self.save()


class ShippingOrder(models.Model):
    first_name = models.CharField('Имя', max_length=50)
    last_name = models.CharField('Фамилия', max_length=50)
    email = models.EmailField('Email', )
    phone = models.IntegerField('Телефон', blank=False)
    city = models.CharField('Город', max_length=100, default='Одесса')
    street = models.CharField('Улица', max_length=200)
    house = models.CharField('Дом', max_length=50)
    apartment = models.CharField('Квартира', max_length=20, blank=False)
    front_door = models.PositiveIntegerField('Парадная', blank=False, null=True)
    floor = models.IntegerField('Этаж', blank=False, null=True)
    number_persons = models.PositiveIntegerField('Кол-во персон:', default=1)
    comment = models.CharField('Комментарий', max_length=300, blank=False)
    type_payment = models.CharField('Способ оплаты', max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'ShippingOrder{}'.format(self.id)

project/pizza/forms.py
from django.forms import ModelForm
from django import forms
from .models import Pizza, ShippingOrder


class PizzaForm(ModelForm):
    class Meta:
        model = Pizza
        fields = ['name', 'price', 'size', 'description', 'available',
                  'ingredient']


class PizzaPriceUpdateForm(forms.Form):
    value = forms.DecimalField(max_digits=7, decimal_places=2)

    def create_object(self):
        Pizza.objects.create(
            value=self.cleaned_data.get('value'),
        )


class PizzaSortedForm(forms.Form):
    sort_order = forms.ChoiceField(
        label='Сортировка',
        required=False,
        choices=[
            ['name', 'по алфавиту'],
            ['price', 'цена по возрастанию'],
            ['-price', 'цена по убыванию'],
        ])


class AddPizzaToOrderForm(forms.Form):
    count = forms.IntegerField()
    pizza_id = forms.IntegerField()


class ShippingOrderForm(ModelForm):
    apartment = forms.CharField(required=False)
    front_door = forms.ImageField(required=False)
    floor = forms.ImageField(required=False)
    comment = forms.CharField(required=False)
    type_payment = forms.ChoiceField(required=False, choices=[
        ['cash', 'Наличными при получении'],
        ['card', 'Оплата картой']
    ])

    class Meta:
        model = ShippingOrder
        fields = ['first_name', 'last_name', 'email', 'phone', 'city',
                  'street', 'house', 'apartment', 'front_door',
                  'floor', 'number_persons', 'type_payment', 'comment', ]

project/pizza/views.py
from .forms import PizzaForm, PizzaPriceUpdateForm, PizzaSortedForm, \
    AddPizzaToOrderForm, ShippingOrderForm
from django.views.generic import ListView, FormView, UpdateView, TemplateView
from django.http import HttpResponseRedirect
from .models import Pizza, Order, InstancePizza


class PizzaHomeView(ListView):
    model = Pizza
    template_name = 'home.html'

    def get_queryset(self):
        sort = self.request.GET.get('sort_order', 'name')
        return Pizza.objects.all().order_by(sort)

    def get_context_data(self,  *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data'] = Pizza.objects.all().count()
        context['list'] = Pizza.objects.values_list('name', flat=True)
        context['form'] = PizzaSortedForm
        context['order'] = Order.objects.first()
        return context


class PizzaFormAddView(FormView):
    template_name = 'form_pizza_add.html'
    form_class = PizzaForm
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class PizzaUpdateView(UpdateView):
    form_class = PizzaForm
    model = Pizza
    template_name = 'form_pizza_add.html'
    success_url = '/'


class PizzaPriceUpdateView(FormView):
    template_name = 'pizza_price_update.html'
    form_class = PizzaPriceUpdateForm
    success_url = '/'

    def form_valid(self, form):
        value = form.cleaned_data
        pizzas = Pizza.objects.all()
        for pizza in pizzas:
            pizza.price = pizza.price + value['value']
            pizza.save()
        return super().form_valid(form)


class AddPizzaToOrderView(FormView):
    form_class = AddPizzaToOrderForm
    success_url = '/'

    def form_valid(self, form):
        order = Order.objects.first()
        if not order:
            order = Order.objects.create()

        pizza_id = form.cleaned_data.get('pizza_id')
        instance_pizza = InstancePizza.objects.filter(pizza_template=pizza_id)

        if instance_pizza:
            print('ТАКАЯ ПИЦА ЕСТЬ')
            instance_pizza = InstancePizza.objects.get(pizza_template=pizza_id)
            count = form.cleaned_data.get('count')
            instance_pizza.count += count
            instance_pizza.save()

        else:
            count = form.cleaned_data.get('count')
            pizza_id = form.cleaned_data.get('pizza_id')
            pizza = Pizza.objects.get(id=pizza_id)
            instance_pizza = InstancePizza.objects.create(
                name=pizza.name,
                size=pizza.size,
                price=pizza.price,
                count=count,
                pizza_template=pizza
            )

            order.pizzas.add(instance_pizza)
        order.save_full_price()
        return super().form_valid(form)

    def del_instance(self, id):
        order = Order.objects.first()
        instance = InstancePizza.objects.get(id=id)
        instance.delete()
        order.save_full_price()
        return HttpResponseRedirect("/cart")


class PizzaCartView(TemplateView):
    template_name = 'cart.html'

    def get_context_data(self, **kwargs):
        context = super(PizzaCartView, self).get_context_data(**kwargs)
        context['order'] = Order.objects.first()
        return context


class ShippingOrderView(FormView):
    template_name = 'shipping.html'
    form_class = ShippingOrderForm
    success_url = 'create/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ShippingOrderView, self).get_context_data(**kwargs)
        context['order'] = Order.objects.first()
        return context


class HomePageCreateOrder(TemplateView):

    template_name = 'created.html'

project/pizza/templates/cart.html
{% extends "index.html"  %}
{% block application %}

<h1>cart</h1>
{% for pizza in order.pizzas.all %}
<div class=" row p-2 mb-2 bg-white text-dark border border-secondary" >
    <div class="col-lg-3 col-sm-3 col-xs-12" style="height: 100px; line-height: 100px;">
        <img  src="{{pizza.pizza_template.image.url}}" style="width: 100px; height: 100px;" />
    </div>
    <div  class="col-lg-3 col-sm-3 col-xs-12 mob-fix" style="height: 100px; line-height: 100px;">
        {{pizza.name}}
    </div>
    <div class="col-lg-2 col-sm-2 col-xs-12 mob-fix" style="height: 100px; line-height: 100px;">
        {{pizza.price}}
    </div>
    <div class="col-lg-1 col-sm-2 col-xs-12 mob-fix" style="height: 100px; line-height: 100px;">
        {{pizza.count}}
    </div>
    <div class="col-lg-3 col-sm-2 col-xs-12 mob-fix" style="height: 100px; line-height: 100px;">
        <form action="/cart/" method="post">
             <div class="form-group mr-sm-2">
                 <input name="pizza_id" value="{{pizza.id}}" hidden>
                  <a href="/del_instance/{{pizza.id}}" class="btn btn-danger btn-sm" role="button"> удалить </a>
             </div>
        </form>
    </div>
  </div>
{% endfor %}
<hr class="mb-4">
 <div class="col-md-12">
     <form action="shipping/">
         <div class="row">
         <div class="col-md-6">
             <button class="btn btn-success"> Оформить заказ </button>
         </div>
         <div class="col-md-6">
             <h5 class="text-danger">СУММА = {{ order.full_price }} грн.</h5>
         </div>
         </div>
     </form>
 </div>

{% endblock%}

project/pizza/templates/created.html
{% extends "index.html"  %}
{% block application %}

<h1 align="center"> Спасибо за заказ </h1>

{% endblock%}

project/pizza/templates/footer.html
{% load static %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">&copy; 2019</small>
      </div>
<!--      <div class="col-6 col-md">-->
<!--        <h5>Features</h5>-->
<!--        <ul class="list-unstyled text-small">-->
<!--          <li><a class="text-muted" href="#">Cool stuff</a></li>-->
<!--          <li><a class="text-muted" href="#">Random feature</a></li>-->
<!--          <li><a class="text-muted" href="#">Team feature</a></li>-->
<!--          <li><a class="text-muted" href="#">Stuff for developers</a></li>-->
<!--          <li><a class="text-muted" href="#">Another one</a></li>-->
<!--          <li><a class="text-muted" href="#">Last time</a></li>-->
<!--        </ul>-->
<!--      </div>-->
<!--      <div class="col-6 col-md">-->
<!--        <h5>Resources</h5>-->
<!--        <ul class="list-unstyled text-small">-->
<!--          <li><a class="text-muted" href="#">Resource</a></li>-->
<!--          <li><a class="text-muted" href="#">Resource name</a></li>-->
<!--          <li><a class="text-muted" href="#">Another resource</a></li>-->
<!--          <li><a class="text-muted" href="#">Final resource</a></li>-->
<!--        </ul>-->
<!--      </div>-->
<!--      <div class="col-6 col-md">-->
<!--        <h5>About</h5>-->
<!--        <ul class="list-unstyled text-small">-->
<!--          <li><a class="text-muted" href="#">Team</a></li>-->
<!--          <li><a class="text-muted" href="#">Locations</a></li>-->
<!--          <li><a class="text-muted" href="#">Privacy</a></li>-->
<!--          <li><a class="text-muted" href="#">Terms</a></li>-->
<!--        </ul>-->
<!--      </div>-->
    </div>
  </footer>

project/pizza/templates/form_pizza_add.html
{% extends "index.html"  %}
{% block title %} Pizza add {% endblock %}
{% block h1 %} Добавьте новую пиццу {% endblock %}
{% block application %}

    <form method="post"> {% csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Сохранить">
    </form>
    <p>
        <form action="/">
            <button> ОТМЕНА </button>
        </form>
    </p>

{% endblock %}

project/pizza/templates/header.html
{% load static %}
<div class="page-header ">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h3 class="my-0 mr-md-auto font-weight-normal">Pizza-BEST!!</h3>
        <nav class="my-2 my-md-0 mr-md-3">
            <a href="/admin/"><img class="text-hide" src="{% static 'images/cog.png'%}" alt="Admin"> </a>
            <a href="{% url 'cart'%}"><img class="text-hide" src="{% static 'images/shopping_cart.png'%}"
                                           alt="Cart"></a>
            <a>({{ order.pizzas.all|length }})</a>
        </nav>
        <a href="{% url 'home'%}"> <img class="text-hide" src="{% static 'images/home2.png'%}" alt="Home"></a>
    </div>
</div>

project/pizza/templates/home.html
{% extends "index.html"  %}
{% block application %}
<p> IP = {{ip}}</p>
<div class="row ">
    {% for pizza in object_list%}
    <div class="col-lg-4 col-md-6 mb-4 ">
        <div class="card h-100 border border-secondary img-thumbnail">
            {% if pizza.image %}
            <a href="#"><img class="card-img-top " src="{{pizza.image.url}}" alt=""></a>
            {% endif %}
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">{{pizza.name}}</a>
                </h4>
                <h4 class="text-danger">{{pizza.price}} грн.</h4>
                <p class="card-text">{{pizza.description}}</p>
            </div>
            <div class="card-footer ">
                <form action="/add-pizza-to-order/" method="post" class="form-inline">
                    <div class="form-group mr-sm-2">
                        <input name="pizza_id" value="{{pizza.id}}" hidden>
                        <input type="number" name="count">
                        <input class="btn btn-success" type="submit" value="Добавить">
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

project/pizza/templates/index.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css">
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title> {% block title %} Pizzas {% endblock %}</title>
        <style>
            body { background: #E0FFFF; color: #6c757d;}
        </style>
    </head>
<body>

<div class="container">
    {% include "header.html" %}
        <h2> {% block h2 %} {% endblock %} </h2>
        <p>{% now "jS F Y H:i" %}</p>

            {% block application %}

            {% endblock %}
    {% include "footer.html"%}
</div>
</body>
</html>

project/pizza/templates/pizza_home.html
{% extends "index.html"  %}
{% block title %} Pizzas {% endblock %}
{% block h2 %} Список пицц {% endblock %}
{% block application %}

    <p><h3> Количество = {{data}} </h3></p>
    <p><h5>{{list}}</h5></p>
    <hr color="#6F9110">
    <ul>
        {% for pizza in object_list %}
        {% if pizza.available %}
        <li type="1">
            <p>
                {{pizza.name|upper}} : цена = {{pizza.price}} грн. (Наличие - {{pizza.available}})
                <a href="/pizza-update/{{pizza.id}}/edit"> - edit </a>
            </p>
        </li>
        {% endif %}
        {%endfor%}
    </ul>
<form action="/" method="get"> {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Применить">
</form>
    <hr color="#6F9110">
<form action="/pizza-price-update/">
    <p><input type="submit" value="Изменить цену"></p>
</form>
<form action="pizza-form-add/">
    <button> Добавить пиццу </button>
</form>

{% endblock %}

project/pizza/templates/pizza_price_update.html
{% extends "index.html"  %}
{% block title %} Price update {% endblock %}
{% block h1 %} Введите на сколько хотите изменить цену {% endblock %}
{% block application %}
<div>
    <form action="" method="post"> {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Сохранить">
    </form>
    <br>
        <form action="/">
            <button> ОТМЕНА </button>
        </form>
</div>
{% endblock %}

project/pizza/templates/shipping.html
{% extends "index.html"  %}
{% block application %}

   <div class="container">

      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Ваша корзина</span>
            <span class="badge badge-secondary badge-pill">{{ order.pizzas.all|length }}</span>
          </h4>
          <ul class="list-group mb-3">
            {% for pizza in order.pizzas.all %}

            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{pizza.name}}</h6>
                <small class="text-muted"> количество - {{pizza.count}}</small>
              </div>
              <span class="text-muted">{{pizza.price}} грн.</span>
            </li>{% endfor %}
            <li class="list-group-item d-flex justify-content-between">
                <span>ИТОГО :</span>
                <strong>{{ order.full_price }} грн.</strong>
            </li>
          </ul>
        </div>

      <!-- Форма заполнения контактов клиента -->
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Оформление заказа</h4>
          <form class="needs-validation"   method="post">

            <div class="row">
              <div class="col-md-6 mb-3">
                <label>Имя</label>
                <input type="text" class="form-control" name="first_name" id="id_first_name" required>
              </div>
              <div class="col-md-6 mb-3">
                <label for="id_last_name">Фамилия</label>
                <input type="text" class="form-control"  name="last_name" id="id_last_name" value="" required>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="id_phone">Телефон</label>
                <input type="number" class="form-control" name="phone" id="id_phone" placeholder="380" required>
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_email">Email </label>
                <input type="email" class="form-control" name="email" id="id_email" placeholder="you@example.com" required>
              </div>

            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="id_city">Город</label>
                <input type="text" class="form-control" name="city" id="id_city" placeholder="" required>
              </div>

              <div class="col-md-6 mb-3">
                <label for="id_street">Улица</label>
                <input type="text" class="form-control" name="street" id="id_street" placeholder="" required>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 mb-3">
                <label for="id_house">Дом</label>
                <input type="text" class="form-control" name="house" id="id_house" placeholder="" required>
              </div>
              <div class="col-md-3 mb-3">
                <label for="id_apartment">Квартира</label>
                <input type="text" class="form-control" name="apartment" id="id_apartment" placeholder="" >
              </div>
              <div class="col-md-3 mb-3">
                <label for="id_front_door">Парадная</label>
                <input type="number" class="form-control" name="front_door" id="id_front_door" placeholder="" >
              </div>
              <div class="col-md-3 mb-3">
                <label for="id_floor">Этаж</label>
                <input type="number" class="form-control" name="floor" id="id_floor" placeholder="" >
              </div>
            </div>

            <div class="row">
              <div class="col-md-3 mb-3">
                <label for="id_number_persons">Количество персон</label>
                <input type="number" class="form-control" name="number_persons" id="id_number_persons" placeholder="" required>
              </div>
              <div class="col-md-5 mb-3">
                <label for="id_type_payment"> Способ оплаты</label>
                <select class="custom-select d-block w-100" name="type_payment" id="id_type_payment" required>
                  <option value="cash">Наличными при получении</option>
                  <option value="card">Оплата картой</option>
                </select>
              </div>
              <div class="col-md-8 mb-3">
                <label for="id_comment">Коментарий</label>
                <input type="text" class="form-control" name="comment" id="id_comment" placeholder="" >
              </div>
            </div>
            <hr class="mb-4">
              <input type="submit" class="btn btn-success" value="Подтвердить заказ">
          </form>
        </div>
      </div>
    </div>
{% endblock %}

project/pizza/templates/stop_spam_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>STOP</title>
</head>
<body>
    <h1 align="center"> !!!!  STOP   SPAM !!!!  </h1>
</body>
</html>